services:
    mysql:
        build:
            context: ./mysql/
            args:
                MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        restart: always
        ports:
            - "127.0.0.1:${MYSQL_PORT}:3306"
        volumes:
            - "${MYSQL_DATA_VOLUME}:/var/lib/mysql"
        environment:
            - "TZ=Asia/Shanghai"
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=app"

    php:
        build:
            context: ./php/
            args:
                ENV: "${ENV}"
                WWWUSER: "${WWWUSER}"
                WWWGROUP: "${WWWGROUP}"
        restart: always
        expose:
            - "9000"
        depends_on:
            - mysql
        volumes:
            - "${CODE_VOLUME}:/var/www/html"

    nginx:
        build: ./nginx/
        restart: always
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - php
        volumes:
            - "${CODE_VOLUME}:/var/www/html"
